#!/usr/bin/env bash
set -euo pipefail

: "${KSU_TYPE:?}"
: "${DEFCONFIG:?}"

if [ "$KSU_TYPE" = "none" ]; then
  exit 0
fi

cat >> "$DEFCONFIG" <<'EOF'
CONFIG_KSU=y
CONFIG_BBG=y
EOF

case "$KSU_TYPE" in
  *-susfs)
    cat >> "$DEFCONFIG" <<'EOF'
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_SUS_MAP=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
EOF
    ;;
esac
